apiVersion: apps/v1
kind: Deployment

metadata:
  name: employee-enterprise

spec:
  replicas: 3

  selector:
    matchLabels:
      app: employee-enterprise

  template:
    metadata:
      labels:
        app: employee-enterprise

    spec:
      containers:
      - name: employee-enterprise

        image: employeeacrdheva01.azurecr.io/employee-enterprise:v1

        ports:
        - containerPort: 5000